### ISSUE TITLE
Missing version tags

### ISSUE THREAD

**Issue by GitMirar** [google/rekall#132]
At least in revision e57446e proper version tags are missing which leads to the version string "0+unknown" which in turn breaks the windows installer build.

**Comment by scudette** [comment]
The way this is supposed to work is that the version is derived from the
git tags. If you don't have git and you are using the git repo to install
then it would show this version because it can't work out what the version
is supposed to be.

Normally when you make a release you do setup.py sdist which then replaces
the _version file with a frozen fixed version. So uses that don't have git
can install.

So you should install from an sdist first.

**Comment by scudette** [comment]
This should no longer be an issue because versions are now committed in files instead of relying on git tags which do not always sync.

The version is calculated as the number of commits since the last full version sync if you are in a git repo or just the last version if not.

Prior to release we run the version.py script and it updates the fixed version everywhere.
