### ISSUE TITLE
Winpmem 2.1 RAW Memory Image Unusable

### ISSUE THREAD

**Issue by dsweet04** [google/rekall#137]
When imaging memory using winpmem_2.1.exe and the "--format raw" switch, the memory image created is unusable in other tools such as volatility and redline. The image is appending the contents of the drivers to the end of the raw memory output requiring a further extraction of Physical Memory with "--export PhysicalMemory -o JustPhysicalMemory.raw" to be usable. Is this the expected functionality? With winpmem_1.6.2.exe the correct raw physical memory only output was created. Is there a reason the the loaded drivers are also being appended to the raw memory dump with 2.1?

Further we are unable to extract the physical memory stream from an aff4 formatted image and use redline or volatility as well. It seems that the physical memory stream when extracted from an aff4 image created with winpmem_2.1.exe is not being generated as expected. This is forcing us to create a raw memory image with 1.6.2 so that we can utilize all the tools available and an aff4 formatted image with 2.1 to capture as complete of an image of the memory space as possible.

**Comment by scudette** [comment]
Hi Daniel,
   There is a misunderstanding here of what exactly the --format switch does that I hope to clarify.

Winpmem 2.1 **always** stores the files in AFF4 containers. AFF4 containers just store multiple streams, the physical memory being one of the streams (the drivers etc are other streams). When I say an "AFF4 container" it means one of the currently supported container types of the AFF4 library. There are currently (only) two types of containers we support: the **ZipFile** style and the **Directory** style. Both are AFF4 containers because they can both support having multiple streams (an AFF4 container should be able to store multiple streams and have metadata - so the bar is pretty low as to what could qualify :)

The **--format** flag just controls the format the memory image will take inside the container - it can be raw, elf, or map (the -h flag explain about each). It does not say anything about the AFF4 container that will be used to store the image. By default winpmem 2.1 uses the **ZipFile** container to store images which is why, as you have noticed, when you write a raw image it looks like it appends other data to the end. It actually does not do that, it just writes a Zip file with a really big (uncompressed) raw file inside it. You can verify this by unzipping the resulting file or listing it with unzip -l. Note that when you choose RAW format it will not compress the memory stream inside the zipfile because the memory image must be seekable for Rekall to be able to use it and you can not seek inside a single compressed zip member.

If you want to use the image with other tools you could simply use a Directory container. You do this by first creating a directory and then telling winpmem to write the image inside it:

```
C:\Users\vagrant>mkdir test
C:\Users\vagrant>Downloads\winpmem_2.1.exe --format raw -o test\
Driver Unloaded.
CR3: 0x0000187000
 3 memory ranges:
Start 0x00001000 - Length 0x0009E000
Start 0x00100000 - Length 0xDFEF0000
Start 0x100000000 - Length 0x120000000
E0415 10:44:41.405839  2140 aff4_file.cc:138] Can not open file C:\Users\vagrant\test\container.description :The system cannot find the file specified.
E0415 10:44:41.421464  2140 aff4_file.cc:138] Can not open file C:\Users\vagrant\test\information.turtle :The system cannot find the file specified.
Creating output AFF4 Directory structure.
Dumping Range 0 (Starts at 1000, length 9e000)
Dumping Range 1 (Starts at 100000, length dfef0000)
Dumping Range 2 (Starts at 100000000, length 120000000)
 Reading 0x8000  0MiB / 8191MiB 0MiB/s
 Reading 0x4f40000  79MiB / 8191MiB 297MiB/s
 Reading 0x8378000  131MiB / 8191MiB 196MiB/s
 Reading 0xbe58000  190MiB / 8191MiB 221MiB/s
 Reading 0xf8a8000  248MiB / 8191MiB 219MiB/s
```

Note the warning message about not being able to open the metadata - As I mentioned an AFF4 container is simply something that can hold streams and have metadata. This means it is trying to read the metadata but there is no metadata there yet.

You can just look inside the directory:
```
C:\Users\vagrant>dir test
 Volume in drive C has no label.
 Volume Serial Number is 40C9-E0AB

 Directory of C:\Users\vagrant\test

04/15/2016  10:47 AM    <DIR>          .
04/15/2016  10:47 AM    <DIR>          ..
04/15/2016  10:47 AM            68,096 C%3a%2fWindows%2fSysNative%2fdrivers%2f1394bus.sys
04/15/2016  10:47 AM           229,888 C%3a%2fWindows%2fSysNative%2fdrivers%2f1394ohci.sys
04/15/2016  10:47 AM           334,208 C%3a%2fWindows%2fSysNative%2fdrivers%2facpi.sys
04/15/2016  10:47 AM            12,800 C%3a%2fWindows%2fSysNative%2fdrivers%2facpipmi.sys
04/15/2016  10:47 AM           491,088 C%3a%2fWindows%2fSysNative%2fdrivers%2fadp94xx.sys
04/15/2016  10:47 AM           339,536 C%3a%2fWindows%2fSysNative%2fdrivers%2fadpahci.sys
....
04/15/2016  10:47 AM            22,096 C%3a%2fWindows%2fSysNative%2fdrivers%2fwimmount.sys
04/15/2016  10:47 AM            52,096 C%3a%2fWindows%2fSysNative%2fdrivers%2fwinhv.sys
04/15/2016  10:47 AM            14,336 C%3a%2fWindows%2fSysNative%2fdrivers%2fwmiacpi.sys
04/15/2016  10:47 AM            16,464 C%3a%2fWindows%2fSysNative%2fdrivers%2fwmilib.sys
04/15/2016  10:47 AM            21,504 C%3a%2fWindows%2fSysNative%2fdrivers%2fws2ifsl.sys
04/15/2016  10:47 AM            87,040 C%3a%2fWindows%2fSysNative%2fdrivers%2fWUDFPf.sys
04/15/2016  10:47 AM           198,656 C%3a%2fWindows%2fSysNative%2fdrivers%2fWUDFRd.sys
04/15/2016  10:47 AM                43 container.description
04/15/2016  10:47 AM            75,380 information.turtle
04/15/2016  10:47 AM     4,831,838,208 PhysicalMemory
04/15/2016  10:47 AM               266 PhysicalMemory%2finformation.yaml
             286 File(s)  4,872,002,777 bytes
               2 Dir(s)   2,193,993,728 bytes free
```

You will see all the files there including a really huge RAW memory stream.

The reason we do it this way is that it kills all the birds at once! Rekall understands proper AFF4 containers and will actually be able to look at the metadata in the directory and be able to use all the extra files we collected by itself. For example, it will just open the kernel image to get the profile GUID without needing the scan for it in memory (this speeds up the initial bootstrap profile search). On Linux Rekall can use the same thing to grab /proc/kallsyms to lookup the index so it can just get the right profile from the repository without user interaction at all.

At the same time, older tools like Volatility can just blindly use the raw format and ignore the metadata and additional files that were collected - so everyone wins!

**Comment by scudette** [comment]
While writing this answer I found a small bug in the ELF image writing (RAW is fine) which caused WinPmem to truncate the image at 4GB.

I had fixed this here:
https://github.com/google/aff4/commit/e4ac4fffe4e31d2be043c495fb46d984b6bfa494#diff-f3036b39b9630127ba74923d7166ab83L334

I also made a new release _winpmem_2.1.post1.exe_ which fixes this issue.

**Comment by dsweet04** [comment]
Awesome explanation. This is perfect for what we need and clarifies things greatly for me I was trying to understand with the format used. AFF4 container with a single raw formatted PhysicalMemory file is exactly what I need and will work with everything.
