### ISSUE TITLE
hooks_inline doesn't see hooks

### ISSUE THREAD

**Issue by yuzvir** [google/rekall#138]
I've found a problem in 'hooks_inline' (apihooks.py) plugin - it skips hooks because some addresses resolves into 'vad_0x????????+smth'.

```
            # Try to resolve the destination into a name.
            destination_name = self.session.address_resolver.format_address(
                destination, max_distance=2**64)

            # We know about it. We suppress the output for jumps that go into a
            # known module. These should be visible using the regular vad
            # module.
            if destination_name:
                destination = destination_name
            else:
                destination = "%#x" % destination
                hook_detected = True
```

**Comment by scudette** [comment]
Thanks for reporting. The address resolver was changed recently to name every known memory region with something. This of course meant that the hook detection algorithm which was previously only looking for unnamed regions, thinks that now every region is known and therefore is not a hook.

This logic is fixed in the current release - regions named like vad_* are considered suspicious and reported. 

Thanks for reporting this bug.
