### ISSUE TITLE
Rekall 1.5.0 Furka giving errors when executed.

### ISSUE THREAD

**Issue by dsweet04** [google/rekall#140]
I've tried now on a Windows 8.1 system as well as a Windows 2012 Server system and I'm getting errors for Rekall_1.5.0_Furka_x64.exe when just running rekal.exe from command line with no arguments. I'm getting the same when trying --live or any other command including -h or --help. 

```
C:\Program Files\Rekall>rekal.exe
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "c:\users\mic\appdata\local\temp\pip-build-tl5cfj\pyinstaller\PyInstaller
\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\rekall_gui\plugins\webconsole_plugin.py", line 51, in <mod
ule>
  File "c:\users\mic\appdata\local\temp\pip-build-tl5cfj\pyinstaller\PyInstaller
\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\manuskript\server.py", line 17, in <module>
  File "site-packages\rekall\resources.py", line 62, in get_resource
IOError: Unable to find resource static
rekal returned -1
```

**Comment by scudette** [comment]
Thanks for the bug report. There seems to be a problem with the static directory not being located where it is expecting it. If you cd into C:\Program Files\Rekall\webconsole\ then it finds the static directory ok.

I think the problem is that pyinstaller is putting resources in locations where the packed executable is not able to find them. I will make a new build shortly. Until then please either use the pip installation method (http://rekall-forensic.blogspot.ch/2015/09/installing-rekall-on-windows.html) or run from the above directory.

Thanks kindly for reporting.

**Comment by scudette** [comment]
This release is superseded by 1.5.1 which should have the issue fixed. Thanks for reporting.
