### ISSUE TITLE
Rekall never exits when using autodetect_build_local none and no profile available 

### ISSUE THREAD

**Issue by dsweet04** [google/rekall#181]
Running `rekal.exe --live --home "C:\Program Files (x86)\Tanium\Tanium Client\Tools\IR\Rekall" --autodetect_build_local none --format data pslist` rekall never exits if a local profile is unavailable. Last line Found RSDS repeats indefinitely until killed. 

<img width="641" alt="screen shot 2016-09-06 at 6 05 23 pm" src="https://cloud.githubusercontent.com/assets/5368247/18292821/616c0e42-745d-11e6-92a2-f67c61b97e10.png">

**Comment by scudette** [comment]
Hi Daniel,
  I think whats happening here is that Rekall is trying to use the kernel image detector for every hit on RSDS signature. This is because it inherits from the RSDS detector so it accidentally registers the RSDS keyword as interesting:

https://github.com/google/rekall/blob/master/rekall-core/rekall/plugins/guess_profile.py#L397

So every time the scanner finds the string RSDS it calls the windows kernel detector to re-check the kernel file on disk (which has not changed since last time so this is pointless). Because we do not build local profiles this is just going to fail and Rekall will keep looking. (Rekall caches the fact that profile building didnt work last time so its very fast each time).

So yeah there is a small bug here because we do a bit more work than we need to, but this should not spin forever (i.e. it will eventually fail). Each log message "Found RSDS" actually refers to a different offset in the image which is checked. So it will eventually give up but it will take a long time because it will be checking a lot of offsets.

I think if you specify a short scan length then it will fail earlier:
--autodetect_scan_length 10000000

but then if the auto detector falls back to the RSDS scanner it will fail to find some images (but fail earlier). We previously played with that parameter - too low and it could fail to detect the RSDS signature, too high and it took a long time to detect. It used to default to a small 1gb but this is insufficient for images which may be very large. I think on live systems the kernel detector should work almost always and so maybe for live images it is better to set the scan length pretty low.

I think in the next release we might adjust some of these with the user specifies --live: perhaps disable the rsds scanner completely and only enable the one for the correct OS - linux detector on linux systems etc.

**Comment by dsweet04** [comment]
So under the scenario that you are running with `--live`, shouldn't the kernel file always be available for use? Also, if `--autodetect_build_local none` is specified, what is the point of searching for a profile unless one is already found to use? Or is there a way for me to disable autodetection completely so I can just specify the exact profile to use and do the check for the presence of the profile before running?

**Comment by scudette** [comment]
That setting means that if the profile is not found in the profile
repository, then it will contact Microsoft's symbol server and build a
profile locally. It still needs to search for a profile and try to get it
from the repository.

If you already have a profile in advance then you can just specify it using
the --profile flag. In that case rekall will not try to auto detect
anything and just use that profile. If it's not right though the analysis
will fail. You can either specify a profile name which will be fetched from
the repository or the path to a profile json file.

**Comment by dsweet04** [comment]
Checking for the profiles existence before executing rekal.exe to avoid my previous issues in the wrapper code seems to be the safest and simplest solution. That way I only execute if the profile is available and when it is I use the `--profile` flag.

**Comment by scudette** [comment]
BTW when Rekall is running inside GRR we have CPU quota enforced by GRR. It might be nice to have a similar feature with Rekall itself? How about --cpu_quota 300 sec per plugin and then raise if we exceed it?

**Comment by dsweet04** [comment]
This would be greatly appreciated. We are having a lot of difficulties in virtualized environment without this type of feature.
