### ISSUE TITLE
Memory leak in winpmem driver

### ISSUE THREAD

**Issue by hexadite-virnik** [google/rekall#183]
In the function `AddMemoryRanges` at https://github.com/google/rekall/blob/master/tools/windows/winpmem/winpmem.c#L58
`MmPhysicalMemoryRange` is not freed in case that `len < required_length`.

**Comment by scudette** [comment]
You are right :-).

We wont be able to fix this at this time because we would need to re-sign the driver and new drivers have to go through much more complicated process for signing. Given that the leak only occurs if the caller fails to allocate enough memory this is not really like to be a problem in practice. So I will close this bug with wont fix, but thanks for the feed back.
