### ISSUE TITLE
Rekall Debian package issues

### ISSUE THREAD

**Issue by noxdafox** [google/rekall#192]
Greetings,

I'd like to install Rekall via Debian package and use its APIs.

I successfully built the .deb package and installed on my machine but when I try to import Rekall in my Python project the module is nowhere to be found.

I also tried to call the command line tool with no success. 

Am I missing something?

**Comment by scudette** [comment]
The standard Debian package we build creates a self contained virtual environment for running Rekall. We do not support installing Rekall into the system as this is a very error prone way to install python packages. This is why it is unexpected that you should be able to import into a project running from the system python (because we dont touch it or install into the shared python folder).

If you want to use Rekall in your own python code you need to pip install it into a virtual environment.

The commandline tool is installed into the virtual environment (Should be `/usr/share/python/rekall-forensic/bin/rekal`). We presently do not symlink it into /usr/bin/ (but we will in the next release).

**Comment by noxdafox** [comment]
Thanks for the explanation. It seems Debian got rekall in stretch so we will see it in the next stable release: https://packages.debian.org/stretch/rekall-core
