### ISSUE TITLE
Python script fails unless run in Etzel

### ISSUE THREAD

**Issue by Oviatt** [google/rekall#250]
Below is a script written for me by my Python guy:
import sys
saveout = sys.stdout
fh = open('info.txt', 'w')
sys.stdout = fh
info
sys.stdout = saveout
fh.close ()

 It works beautifully in Etzel. I copy this script and paste it into the shell and it runs, producing an output file with whatever rekal plugin I gave it. For instance the script above would create a text file called info.txt that contained the results of the info plugin. When I run it in any Rekal version above Etzel, the script does not complete as shown below - after import sys it acts like there's no CR/LF (I think) and the resulting output file is zero bytes.
> import sys
  ...: saveout = sys.stdout
  ...: fh = open('info.txt', 'w')
  ...: sys.stdout = fh
  ...: info
  ...: sys.stdout = saveout
  ...: fh.close ()

If I copy or type each line individually and give it a hard return on the keyboard, it drops to a new > prompt and I can walk through the entire script and get the desired output file. When it works, I can load up as many plugins as I want and let it rip. It's a walkaway. When it's done I have multiple text files containing the data I want from any plugin.

I am a rookie plundering Python programmer at best, and I have no clue how to resolve this other than stay with Etzel. Any ideas? You can try it yourself and see!

Thank you.

**Comment by scudette** [comment]
I suspect the reason the script does not work is because the plugin is never executed. Because we use IPython in the console we can have it automatically execute plugins. So if you just enter a plugin name (say "info") and press enter, IPython automatically adds the () to make info() which runs it. This is just a user friendly feature. In reality everything in the console is python and if you want the plugin to run you need to add the () to execute it. I suspect if you just replace info with info() it would work.

Aside from that, it appears that you want to just save the output of the plugin into a file and that is a very weird way to go about doing that. Why not simply:

```
info output="info.txt"
```
Or 
```
info(output="info.txt")
```
Also since calling unicode() on a plugin returns the output as a unicode string
```
with open("info.txt", "wb") as fd:
     fd.write(unicode(info()))
```

**Comment by Oviatt** [comment]
Thank you very much. This is working for me:
 info(output="info.txt") 
I can stack up a list of plugins I want to run and walk away. When it’s done, I have a text file for each one that I can parse.

**Comment by scudette** [comment]
If you are going to parse it then you probably want it to be written in
json format. Use the --format data to get a machine readable json output.

**Comment by Oviatt** [comment]
Very good Sir – thank you! As you can probably tell, I am not well versed in Python!
