### ISSUE TITLE
failed to install rekall-agent

### ISSUE THREAD

**Issue by nssamphone** [google/rekall#321]
During installing latest version of  google **Rekall** Forensic framwork, at the step of installing "rekall-agent" it says: "Failed building wheel for readline"  

I am installing it on Kali Linux(2016-02) default python version is 2.7.12  
at the step of installing rekall-agent I face exception and error.here is the error part with verbose switch:  

        ============ Building the readline extension module ============
    
      running bdist_wheel
      running build
      running build_ext
      building 'readline' extension
      creating build
      creating build/temp.linux-x86_64-2.7
      creating build/temp.linux-x86_64-2.7/Modules
      creating build/temp.linux-x86_64-2.7/Modules/2.x
      x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I. -I/usr/include/python2.7 -c Modules/2.x/readline.c -o build/temp.linux-x86_64-2.7/Modules/2.x/readline.o -Wno-strict-prototypes
      creating build/lib.linux-x86_64-2.7
      x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/Modules/2.x/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.linux-x86_64-2.7/readline.so
      /usr/bin/ld: cannot find -lncurses
      collect2: error: ld returned 1 exit status
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    error
      Failed building wheel for readline
      Running setup.py clean for readline
      Running command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t5Y300/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
      running clean
      removing 'build/temp.linux-x86_64-2.7' (and everything under it)
      removing 'build/lib.linux-x86_64-2.7' (and everything under it)
      'build/bdist.linux-x86_64' does not exist -- can't clean it
      'build/scripts-2.7' does not exist -- can't clean it
      removing 'build'
    Failed to build readline
    Installing collected packages: readline, rekall
      Running setup.py install for readline ...     Running command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t5Y300/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Gvwo7F-record/install-record.txt --single-version-externally-managed --compile
        running install
        running build
        running build_ext
        building 'readline' extension
        creating build
        creating build/temp.linux-x86_64-2.7
        creating build/temp.linux-x86_64-2.7/Modules
        creating build/temp.linux-x86_64-2.7/Modules/2.x
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I. -I/usr/include/python2.7 -c Modules/2.x/readline.c -o build/temp.linux-x86_64-2.7/Modules/2.x/readline.o -Wno-strict-prototypes
        creating build/lib.linux-x86_64-2.7
        x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/Modules/2.x/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.linux-x86_64-2.7/readline.so
        /usr/bin/ld: cannot find -lncurses
        collect2: error: ld returned 1 exit status
        error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    error
    Cleaning up...
      Removing source in /tmp/pip-build-t5Y300/readline
    Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t5Y300/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Gvwo7F-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-t5Y300/readline/
    Exception information:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
        prefix=options.prefix_path,
      File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 878, in install
        spinner=spinner,
      File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 707, in call_subprocess
        % (command_desc, proc.returncode, cwd))
    InstallationError: Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t5Y300/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Gvwo7F-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-t5Y300/readline/

**Comment by scudette** [comment]
This usually means you don't have the ncurses library. For example on
Ubuntu you would install libncurses-dev . There must be a similarly named
package on Kali Linux.

On 23 Nov 2017 12:13 AM, "nssamphone" <notifications@github.com> wrote:

During installing latest version of google *Rekall* Forensic framwork, at
the step of installing "rekall-agent" it says: "Failed building wheel for
readline"

I am installing it on Kali Linux(2016-02) default python version is 2.7.12
at the step of installing rekall-agent I face exception and error.here is
the error part with verbose switch:

    ============ Building the readline extension module ============

  running bdist_wheel
  running build
  running build_ext
  building 'readline' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/Modules
  creating build/temp.linux-x86_64-2.7/Modules/2.x
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall
-Wstrict-prototypes -fno-strict-aliasing -Wdate-time
-D_FORTIFY_SOURCE=2 -g
-fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=.
-fstack-protector-strong -Wformat -Werror=format-security -fPIC
-DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL
-DHAVE_RL_COMPLETION_APPEND_CHARACTER
-DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES
-DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I.
-I/usr/include/python2.7 -c Modules/2.x/readline.c -o
build/temp.linux-x86_64-2.7/Modules/2.x/readline.o
-Wno-strict-prototypes
  creating build/lib.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1
-Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g
-fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2
-g -fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=.
-fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro
-Wdate-time -D_FORTIFY_SOURCE=2 -g
-fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=.
-fstack-protector-strong -Wformat -Werror=format-security
build/temp.linux-x86_64-2.7/Modules/2.x/readline.o
readline/libreadline.a readline/libhistory.a -lncurses -o
build/lib.linux-x86_64-2.7/readline.so
  /usr/bin/ld: cannot find -lncurses
  collect2: error: ld returned 1 exit status
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
error
  Failed building wheel for readline
  Running setup.py clean for readline
  Running command /usr/bin/python -u -c "import setuptools,
tokenize;__file__='/tmp/pip-build-t5Y300/readline/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  running clean
  removing 'build/temp.linux-x86_64-2.7' (and everything under it)
  removing 'build/lib.linux-x86_64-2.7' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-2.7' does not exist -- can't clean it
  removing 'build'
Failed to build readline
Installing collected packages: readline, rekall
  Running setup.py install for readline ...     Running command
/usr/bin/python -u -c "import setuptools,
tokenize;__file__='/tmp/pip-build-t5Y300/readline/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install
--record /tmp/pip-Gvwo7F-record/install-record.txt
--single-version-externally-managed --compile
    running install
    running build
    running build_ext
    building 'readline' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/Modules
    creating build/temp.linux-x86_64-2.7/Modules/2.x
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall
-Wstrict-prototypes -fno-strict-aliasing -Wdate-time
-D_FORTIFY_SOURCE=2 -g
-fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=.
-fstack-protector-strong -Wformat -Werror=format-security -fPIC
-DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL
-DHAVE_RL_COMPLETION_APPEND_CHARACTER
-DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES
-DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I.
-I/usr/include/python2.7 -c Modules/2.x/readline.c -o
build/temp.linux-x86_64-2.7/Modules/2.x/readline.o
-Wno-strict-prototypes
    creating build/lib.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1
-Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g
-fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2
-g -fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=.
-fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro
-Wdate-time -D_FORTIFY_SOURCE=2 -g
-fdebug-prefix-map=/build/python2.7-oH9M6v/python2.7-2.7.12=.
-fstack-protector-strong -Wformat -Werror=format-security
build/temp.linux-x86_64-2.7/Modules/2.x/readline.o
readline/libreadline.a readline/libhistory.a -lncurses -o
build/lib.linux-x86_64-2.7/readline.so
    /usr/bin/ld: cannot find -lncurses
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-build-t5Y300/readline
Command "/usr/bin/python -u -c "import setuptools,
tokenize;__file__='/tmp/pip-build-t5Y300/readline/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install
--record /tmp/pip-Gvwo7F-record/install-record.txt
--single-version-externally-managed --compile" failed with error code
1 in /tmp/pip-build-t5Y300/readline/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py",
line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py",
line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py",
line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py",
line 878, in install
    spinner=spinner,
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py",
line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/bin/python -u -c "import setuptools,
tokenize;__file__='/tmp/pip-build-t5Y300/readline/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install
--record /tmp/pip-Gvwo7F-record/install-record.txt
--single-version-externally-managed --compile" failed with error code
1 in /tmp/pip-build-t5Y300/readline/

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/rekall/issues/321>, or mute the thread

**Comment by nssamphone** [comment]
thank you  @scudette 
`sudo apt-get install libncurses5-dev libncursesw5-dev`
solved this problem, I face another problem but its sth else and if I cannot handle it< I will open another issue for that.
