### ISSUE TITLE
 rekall-core/setup.py cannot locate 'rekall-capstone==3.0.5.post2',

### ISSUE THREAD

**Issue by seth1002** [google/rekall#329]
rekall-core/setup.py cannot locate 'rekall-capstone==3.0.5.post2',

**Comment by scudette** [comment]
Usually when building from head you will need to install dependencies from their respective git head because the packages do not get published until a release is made. Just clone the repo and install it using `pip install /path/to/rekall-capstone` before you try to install rekall from git head.  Then it should not be trying to get it from pypi because the version is satisfied. 

https://github.com/rekall-innovations/rekall-capstone
