### ISSUE TITLE
Building standalone for win32

### ISSUE THREAD

**Issue by DigiAngel** [google/rekall#62]
Topic says it..I see there's a 64-bit standalone which I use, but I need to get a win32 version...I have Visual Studio 2013 Express installed on a Win7 32 bit machine and I have the rekall-1.3.2 source, but I haven't a clue on the next step.  Any assistance would be wonderful...thank you.

**Comment by scudette** [comment]
So we stopped building 32 bit binaries for windows - I guess there is still a use case although we dont use it :-). I can add a 32 bit build to the next release. Until then I can describe basically how to build the binary windows release for 32 bits (its basically the same process as 64 bits anyway).

1. Install python and pip - Pretty easy.... For 32 bit builds I always use c:\python27.32\ which is different than the 64 bit - you can have both architectures installed side by side.
2. Install visual studio - I have VS 2010 express but I am sure VS 2013 will work too.
3. Open a visual studio command prompt - should be a launch icon in the start menu.
4. This is a trick - python expects to use VS 2009 to build its stuff and if you dont do this it will fail with a message like "cant find vcbuildvars" or some such. This makes it find the script where VS 2010 installs it:
```
SET VS90COMNTOOLS=%VS100COMNTOOLS%
```
I guess you might need to change the VS100 to something else for VS 2013.
5. Now you just install it normally - either from pip:

```
c:\python27.32\scripts\pip.exe install rekall
```
Or
```
c:\python27.32\python.exe setup.py install
```

This should pull in all the dependencies and build everything (like distorm3 etc). It only takes a few minutes.

6. Now if you want to make an installer package you need to install inno setup which we use to make the installer. There is a bat script which just builds everything for you in `tools\installers\winbuild.bat`. Copy to to say `winbuild_x86.bat` and change so it runs the 32 bit python and a 32 bit copy of `rekall.iss` (also install pyinstaller and point it to that directory):

```
rem Run this batch file from the root rekall directory to build a new Rekall installer.

del /s /q build
del /s /q dist

c:\Python27.32\python.exe c:\Python27\PyInstaller-2.1\pyinstaller.py --onedir -y -i resources\rekall.ico rekall\rekal.py

"c:\Program Files (x86)\Inno Setup 5\ISCC.exe" tools\installers\rekall_x86.iss
```
You can modify the iss file for 32 bit version. The most important thing is to include the `MSVCR100.dll` (probably something else for VS 2013). Otherwise the installation will fail if the user does not have it. For a 32 bit build you need to get it from `c:\windows\system32` (for 64 bit you need to get from `c:\windows\sysnative\`). Also make sure to include `distorm3.dll` (choose the one in the 32 bit python directory). If you want yara you can build and install it too and then add its dll as well.

```
[Files]
; Extra Binaries to add to the package.
Source: C:\Python27.32\Lib\site-packages\distorm3\distorm3.dll; DestDir: {app}\dlls
; Source: C:\Python27.32\DLLs\libyara.dll; DestDir: {app}\dlls

; The ISS installer is a 32 bit app and for this 64 bit build needs to package
; the 64 dll.
Source: C:\Windows\system32\MSVCR100.dll; DestDir: {app}
Source: C:\Windows\system32\MSVCP100.dll; DestDir: {app}
``` 

You can also change some of the other options (like the output file name) - comment out the architecture stuff.

```
;ArchitecturesAllowed=x64
;ArchitecturesInstallIn64BitMode=x64
OutputBaseFilename=Rekall_{#REKALL_VERSION}_{#REKALL_CODENAME}_x86
```

Thats basically it - when you run the bat file it should build with pyinstaller then package with inno setup.

Finally before I forget you need to fix distorm3 so it behaves properly when frozen inside pyinstaller. Distorm3 tries to find its dll but uses \_\_file\_\_ to find it - but this does not exist in a frozen binary so you need to actually edit the distrom3 code _after it is installed_ (if you ever reinstall distorm3 you need to do this hack again). This is actually described in the code (`rekall/plugins/windows/disassembler.py`) but essentially you add this code:

```
# Guess the DLL filename and load the library.
import sys
if getattr(sys, "frozen", None):
  _distorm_path = "dlls"
else:
  _distorm_path = split(__file__)[0]
```

to the beginning of this file `c:\python27.32\lib\site-packages\distrom3\__init__.py` (I sent a patch upstream to fix this issue but it seemed to have missed the last release).

**Comment by DigiAngel** [comment]
Thanks a TON really.  I'll give this a go...I figured since i was building my forensic USB stick I might as well be ready for anything.

**Comment by scudette** [comment]
I automated this process a great deal and now you just need to run a single python script. The process is also outlined in the blog post:

http://rekall-forensic.blogspot.ch/2015/09/installing-rekall-on-windows.html

So Im going to close this bug.

**Comment by DigiAngel** [comment]
Thanks so much!
