### ISSUE TITLE
version_scan multi results for same pdb file

### ISSUE THREAD

**Issue by allewwaly** [google/rekall#68]
When I use rekal version_scan to search for one specific pdb file, such as kernel32 or ntdll, there always comes out two or three results with different GUID. Which one should I choose? The memory image is achieved via winpmem

**Comment by scudette** [comment]
This is actually an excellent question. The `version_scan` plugin is pretty simple - it just scans the physical address space for an RSDS signature which is the structure containing the debug information. Usually (unless specifically configured in Visual Studio) the compiler will add this signature to the PE file and this is how the debugger knows which GUID to use for debugging. The point is that the `version_scan` plugin has absolutely no context about the executable or anything else - its just looking for a small signature of say less than 200 bytes. So for example you might find it inside a network packet if you download an executable or something just as surprising !

But its worth checking and making sure. You can use the `pas2vas` plugin to see which virtual address space maps a particular physical page. For example lets look at a windows 10 image:

```
[1] win10.aff4 16:52:19> version_scan name_regex="ntdll"
  Offset (P)             GUID/Version                         PDB              
-------------- --------------------------------- ------------------------------
0x000018635cbc D30022BB0A414A8E8F44206C20B3EC6D1 wntdll.pdb                    
0x0000236b70f3 D811996F98BC4C5693EAB1B2E3C5EF641 ntdll.pdb                     
0x000024a4d66a 6F035150E9534D46A06E6B120F704C9B1 ntdll.pdb                     
0x0000302a99d4 D5BDA904A7FF452E881F27C9D10DA44E1 ntdll.pdb                     
0x000033044a2c 7CB40EBB68E24F689C03B713A33947BE1 ntdll.pdb                
```

Lets check out the first one (*wntdll.dll*):
```
[1] win10.aff4 16:54:21> pas2vas 0x000018635cbc
   Physical       Virtual      Pid   Name
-------------- -------------- ------ ----
0x000018635cbc 0x0000776aacbc    468 winpmem_2.0.1.
0x000018635cbc 0x0000776aacbc   3840 OneDrive.exe
```
You can see that these are the WoW64 processes (i.e. this is the 32 bit version of the dll mapped into the 32 bit processes).

The next two addresses are in the kernel - not clear why they appear but these are clearly false positives:
```
[1] win10.aff4 16:54:28> pas2vas 0x0000236b70f3
   Physical       Virtual      Pid   Name
-------------- -------------- ------ ----
0x0000236b70f3 0xe000379ce0f3      0 Kernel
0x0000236b70f3 0xe000379ce0f3      4 System

[1] win10.aff4 16:54:57> pas2vas 0x000024a4d66a
   Physical       Virtual      Pid   Name
-------------- -------------- ------ ----
0x000024a4d66a 0xe0003757666a      0 Kernel
0x000024a4d66a 0xe0003757666a      4 System
```

Then the normal dll appears - note how it is mapped into all the processes. It is not copied! The same physical page which occurs only once in the image is just mapped into all the process' address spaces (you might also notice that it is mapped into the same virtual address in each process since ntdll is first to load it rarely needs to be relocated):

```
[1] win10.aff4 16:55:10> pas2vas 0x0000302a99d4
   Physical       Virtual      Pid   Name
-------------- -------------- ------ ----
0x0000302a99d4 0x7ffa506f89d4    260 smss.exe
0x0000302a99d4 0x7ffa506f89d4    332 csrss.exe
0x0000302a99d4 0x7ffa506f89d4    400 wininit.exe
0x0000302a99d4 0x7ffa506f89d4    408 csrss.exe
0x0000302a99d4 0x7ffa506f89d4    472 winlogon.exe
0x0000302a99d4 0x7ffa506f89d4    496 services.exe
0x0000302a99d4 0x7ffa506f89d4    504 lsass.exe
0x0000302a99d4 0x7ffa506f89d4    572 svchost.exe
0x0000302a99d4 0x7ffa506f89d4    616 svchost.exe
....
```

Finally the last GUID appears inside the windows defender process (which seems to have lots of RSDS signatures around the same area - you can check with the `dump` plugin).

```
[1] win10.aff4 16:55:34> pas2vas 0x000033044a2c
   Physical       Virtual      Pid   Name
-------------- -------------- ------ ----
0x000033044a2c 0x0092af7cca2c   1452 MsMpEng.exe
[1] win10.aff4 16:55:38> cc 1452
[1] win10.aff4 16:59:56> dump 0x0092af7cca2c, length=20
    Offset                                   Data                                                Comment                 
-------------- ----------------------------------------------------------------- ----------------------------------------
  0x92af7cca2c 52 53 44 53 bb 0e b4 7c e2 68 68 4f 9c 03 b7 13  RSDS...|.hhO....  
  0x92af7cca3c a3 39 47 be 01 00 00 00 6e 74 64 6c 6c 2e 70 64  .9G.....ntdll.pd  

```

Note also that those other GUIDs are simply not really valid. If we try to download them from the microsoft symbol server it does not have them:
```
[1] win10.aff4 17:07:26> fetch_pdb guid="7CB40EBB68E24F689C03B713A33947BE1", pdb_filename="ntdll.pdb"
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntdll.pdb/7CB40EBB68E24F689C03B713A33947BE1/ntdll.pd_
CRITICAL:rekall.1:Traceback (most recent call last):                                                               
  File "/home/scudette/rekall/rekall/session.py", line 714, in _RunPlugin
    return plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/scudette/rekall/rekall/plugins/tools/mspdb.py", line 162, in render
    pdb_file_data = self.FetchPDBFile(self.pdb_filename, self.guid)
  File "/home/scudette/rekall/rekall/plugins/tools/mspdb.py", line 181, in FetchPDBFile
    url_handler = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

I dont really know what this means? It is interesting why windows defender contains GUIDs of dlls which are publically available (at least not on the public symbol server). Maybe MS use these internally for testing?

**Comment by allewwaly** [comment]
Thanks for your detailed reply. The last finding is interesting. Maybe defender is tested on internal network with private pdb server to increase the complexity to reverse or something evil.
